apiVersion: apps/v1
kind: Deployment
metadata:
  name: pumpkin-api
  labels:
    app: pumpkin-api
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: pumpkin-api

  template:
    metadata:
      labels:
        app: pumpkin-api

    spec:
      containers:
        - name: pumpkin-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: 10
            periodSeconds: 20