apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pumpkin-api
  labels:
    app: pumpkin-api

spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pumpkin-api
            port:
              number: 80