apiVersion: v1
kind: Service
metadata:
  name: pumpkin-api
spec:
  type: {{ .Values.service.type }}

  selector:
    app: pumpkin-api

  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80