name: Terraform Infrastructure

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "terraform/**"
      - ".github/workflows/terraform.yml"      
env:
  KEYVAULT_NAME: pumpkin-kv
  ARM_SUBSCRIPTION_ID: 82ffa9ee-9851-4b3e-9a19-4382b0bf394a
  ARM_TENANT_ID: 360a0677-6f93-41f6-b022-bf79054b212e

jobs:

# ==========================================
# DEV ENVIRONMENT
# ==========================================
  terraform-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -----------------------------
      # Azure Login
      # -----------------------------
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # -----------------------------
      # Get Secrets from Key Vault
      # -----------------------------
      - name: Get Secrets from Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEYVAULT_NAME }}
          secrets: arm-client-id,arm-client-secret

      # -----------------------------
      # Terraform Init
      # -----------------------------
      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}

      # -----------------------------
      # Terraform Validate
      # -----------------------------
      - name: Terraform Validate
        run: terraform validate

      # -----------------------------
      # Terraform Lint
      # -----------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      # -----------------------------
      # Terraform Security Scan
      # -----------------------------
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_AZURE_6,CKV_AZURE_4,CKV_AZURE_7,CKV_AZURE_115,CKV_AZURE_116,CKV_AZURE_117,CKV_AZURE_137,CKV_AZURE_138,CKV_AZURE_139,CKV_AZURE_141,CKV_AZURE_143,CKV_AZURE_163,CKV_AZURE_164,CKV_AZURE_165,CKV_AZURE_166,CKV_AZURE_167,CKV_AZURE_168,CKV_AZURE_169,CKV_AZURE_170,CKV_AZURE_171,CKV_AZURE_172,CKV_AZURE_182,CKV_AZURE_183,CKV_AZURE_226,CKV_AZURE_227,CKV_AZURE_232,CKV_AZURE_233,CKV_AZURE_237,CKV_AZURE_246,CKV2_AZURE_29,CKV2_AZURE_31,CKV_AZURE_115

      # -----------------------------
      # Terraform Plan
      # -----------------------------
      - name: Terraform Plan
        run: terraform plan -input=false -lock-timeout=5m -var="location=westeurope"
        env:
          ARM_CLIENT_ID: ${{ steps.kv.outputs.arm-client-id }}
          ARM_CLIENT_SECRET: ${{ steps.kv.outputs.arm-client-secret }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
      # -----------------------------
      # Terraform Apply
      # -----------------------------
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="location=westeurope"
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}

# ==========================================
# PROD ENVIRONMENT
# ==========================================
  terraform-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/prod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # -----------------------------
      # Azure Login
      # -----------------------------
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # -----------------------------
      # Get Secrets from Key Vault
      # -----------------------------
      - name: Get Secrets from Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEYVAULT_NAME }}
          secrets: arm-client-id,arm-client-secret

      # -----------------------------
      # Terraform Init
      # -----------------------------
      - name: Terraform Init
        run: terraform init
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}

      # -----------------------------
      # Terraform Validate
      # -----------------------------
      - name: Terraform Validate
        run: terraform validate

      # -----------------------------
      # Terraform Lint
      # -----------------------------
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3

      - name: Run TFLint
        run: |
          tflint --init
          tflint

      # -----------------------------
      # Terraform Security Scan
      # -----------------------------
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_AZURE_6,CKV_AZURE_4,CKV_AZURE_7,CKV_AZURE_115,CKV_AZURE_116,CKV_AZURE_117,CKV_AZURE_137,CKV_AZURE_138,CKV_AZURE_139,CKV_AZURE_141,CKV_AZURE_143,CKV_AZURE_163,CKV_AZURE_164,CKV_AZURE_165,CKV_AZURE_166,CKV_AZURE_167,CKV_AZURE_168,CKV_AZURE_169,CKV_AZURE_170,CKV_AZURE_171,CKV_AZURE_172,CKV_AZURE_182,CKV_AZURE_183,CKV_AZURE_226,CKV_AZURE_227,CKV_AZURE_232,CKV_AZURE_233,CKV_AZURE_237,CKV_AZURE_246,CKV2_AZURE_29,CKV2_AZURE_31,CKV_AZURE_115

      # -----------------------------
      # Terraform Plan
      # -----------------------------
      - name: Terraform Plan
        # run: terraform plan -input=false -lock-timeout=5m -var="location=westeurope"
        run: |
          terraform plan \
            -out=tfplan.binary \
            -input=false \
            -lock-timeout=5m \
            -var="location=westeurope"

          terraform show -json tfplan.binary > tfplan.json

        env:
          ARM_CLIENT_ID: ${{ steps.kv.outputs.arm-client-id }}
          ARM_CLIENT_SECRET: ${{ steps.kv.outputs.arm-client-secret }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}

      # -----------------------------
      # OPA policy check
      # -----------------------------
      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/   
          
      # -----------------------------
      # Opa check
      # -----------------------------
      - name: OPA Checking
        run: |
          opa eval --format pretty \
            --input tfplan.json \
            --data policy/terraform.rego \
            "data.terraform.security.deny" > result.txt
            
          cat result.txt

          if grep -q "Public IP is not allowed" result.txt; then
            echo "❌ Policy violation detected. Failing pipeline."
            exit 1
          else
            echo "✅ Policy check passed."
          fi

          if grep -q "\[" result.txt && ! grep -q "\[\]" result.txt; then
            echo "❌ Policy violations detected. Failing pipeline."
            exit 1
          else
            echo "✅ Policy check passed."
          fi
            
      # -----------------------------
      # Terraform Apply
      # -----------------------------
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="location=westeurope"
        env:
          ARM_CLIENT_ID: ${{ env.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ env.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}